export const DEFAULT_ROLE_PERMISSIONS = {
    PLATFORM_ADMIN: [
        'org:manage',
        'users:manage',
        'billing:manage',
        'crm:read',
        'crm:write',
        'tasks:read',
        'tasks:write',
        'documents:read',
        'documents:write',
        'workflows:manage',
        'growth:manage',
        'industry:health',
        'industry:funeral',
        'industry:logistics',
        'industry:trade',
        'mari:ai_chat',
        'mari:ai_actions',
        'mari:knowledge_base',
    ],
    ORGANIZATION_OWNER: [
        'org:manage',
        'users:manage',
        'billing:manage',
        'crm:read',
        'crm:write',
        'tasks:read',
        'tasks:write',
        'documents:read',
        'documents:write',
        'workflows:manage',
        'growth:manage',
        'industry:health',
        'industry:funeral',
        'industry:logistics',
        'industry:trade',
        'mari:ai_chat',
        'mari:ai_actions',
        'mari:knowledge_base',
    ],
    MANAGER: [
        'users:manage',
        'crm:read',
        'crm:write',
        'tasks:read',
        'tasks:write',
        'documents:read',
        'documents:write',
        'workflows:manage',
        'growth:manage',
        'mari:ai_chat',
        'mari:ai_actions',
    ],
    EMPLOYEE: [
        'crm:read',
        'crm:write',
        'tasks:read',
        'tasks:write',
        'documents:read',
        'mari:ai_chat',
    ],
    CUSTOM: [],
};
